### Request for hero
POST https://heroapp-apim.azure-api.net/api/offers/request HTTP/1.1
Content-Type: application/json
Ocp-Apim-Subscription-Key: 53ab7699b93741139e8bc2a6831b1129

{
    "powers": "strength, night vision",
    "firstname": "John",
    "lastname": "Stamp",
    "email": "john.stamp@outlook.com"
}

### Make payment
POST https://.../api/invoices/payment HTTP/1.1
Content-Type: application/json
Ocp-Apim-Subscription-Key: 53ab7699b93741139e8bc2a6831b1129

{
    "offerId": "c6dac254-4d77-4ba6-84a0-74ee60790aec",
    "amount": 1000.00
}